- hosts: workstation
  gather_facts: false
  tasks:
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
      region_name: regionOne
      server: front*
    register: r_os_servers
  
  - debug:
      msg: "{{ r_os_servers.openstack_servers[0].public_v4 }}"


  - name: Add host
    add_host:
      name: "{{ r_os_servers.openstack_servers[0].public_v4 }}"


  - name: capture frontend IP
    set_fact:
      frontendIP: "{{ r_os_servers.openstack_servers[0].accessIPv4 }}"
#
  - debug:
      msg: "{{ frontendIP }}"

  - name: Check webserver for correct response
    uri:
      url: "http://{{ frontendIP }}/index.html"
      return_content: yes
    register: results 

#
  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in results.content"
    tags:
      - osp.smoke

