- hosts: workstation
  gather_facts: false
  tasks:
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
      region_name: regionOne
    register: r_os_servers

  - name: Add host
    add_host:
      name: "{{ item.public_v4 }}"
      group:
        - "{{ item.metadata.group }}"
        - "{{ item.metadata.deployment_name }}"
    loop: "{{ r_os_servers.openstack_servers }}"
    register: fehost
    when: item.metadata.group == 'frontends'

  - name: Print records
    debug:
      msg: "{{ fehost }} "  

  - name: Check webserver for correct response
    uri:
      url: "http://{{ item.accessIPv4 }}/index.html"
      return_content: yes
    register: results
#    delegate_to: localhost
    loop: "{{ r_os_servers.openstack_servers }}"
    when:  item.metadata.group == 'frontends'

  - name: Print records
    debug:
      msg: "{{ results }}"  

#  - name: Fail if 'Ansible has done its job' is not in the page content
#    fail:
#    when: "'Ansible has done its job' not in results"
#    tags:
#      - osp.smoke

