---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

#- name: enable repos
#  copy:
#    src: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo 
#    dest: /etc/yum.repos.d/epel.repo
#    remote_src: yes

 
#- name: install base tools and packages
#  yum:
#    name:
#      - git
#      - python3
#      - pip
#      - ansible
#      - openstacksdk
#      - selinux

#- name: Install openstack library
#  command: pip3 install ansible openstacksdk -U
#  state: installed

