---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: add repo
  template:
    src: repo_template.j2
    dest: /etc/yum.repos.d/epel.repo
   

- name: enable repo 
  shell: yum-config-manager --enable epel.repo 
 
- name: install base tools and packages
  yum:
    name:
      - python3

- name: Install openstack library
  command: pip3 install ansible openstacksdk -U

